"""
Django settings for new_project project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8-lmv%-vsd==f&d20k-dfek-*jh0&cstub*h7978$802#-uf50'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_register',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'new_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'new_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

STATICFILES_DIRS = [BASE_DIR / 'static', ]
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "My Project",  # Title of the admin site
    "site_header": "ESPD 2402",  # Title in the top left corner
    "site_logo": "logo.png",  # Path to your logo
    "login_logo": "logo.png", 
    "welcome_sign": "Welcome ESPD 2402!",
    "user_avatar": None,  # Specify a user avatar field (e.g., "profile_picture")
    "copyright": "My Company © 2024",
    "search_model": "auth.User",  # Add search functionality for specific models
    "show_sidebar": True,  # Enable/disable the sidebar
    "hide_apps": ["sessions"],  # Apps to hide from the admin panel
    "hide_models": ["auth.Group"],  # Models to hide
    "order_with_respect_to": ["auth", "myapp"],  # Organize apps in the sidebar
    "icons": {
        "auth": "fas fa-users",  # FontAwesome icons
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users-cog",
    },
    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},  # Direct link to the user model
        {"name": "Support", "url": "https://example.com/support", "new_window": True},
    ],
}
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",  # Built-in Bootstrap theme (e.g., darkly, cerulean, etc.)
    "navbar": "navbar-dark bg-primary",  # Navbar classes
    "no_navbar_border": True,  # Remove navbar border
    "sidebar": "sidebar-dark-primary",  # Sidebar color
    "sidebar_nav_child_indent": True,  # Indent child items in the sidebar
    "sidebar_nav_flat_style": False,  # Flat style for sidebar links
    "brand_small_text": False,  # Reduce text size of the brand/logo
}
